### ISSUE TITLE
剪贴板取词复制次数能否配置化

### ISSUE THREAD

**Issue by templklklk** [xxNull-lsk/my_dict#2]
你好，我看过你将复制次数从两次改成3次的原因 -- [我的词典：0.2.3开发手记](http://home.mydata.top:8093/?p=83)。
但这应该不是大部分用户会遇到的问题，所以所有用户都被强迫3次不太合理。
能否可配置复制次数，比如默认2次，但可以设置成3次？

**Comment by xxNull-lsk** [comment]
0.6.11版可以设置复制次数了。
