### ISSUE TITLE
能否增加代理服务配置

### ISSUE THREAD

**Issue by templklklk** [xxNull-lsk/my_dict#3]
google翻译很慢，希望能配置代理服务。

另外，谢谢作者开发my_dict，linux上的词典太难用了（要么功能缺失要么配置复杂）。
不知道作者是否用过windows的lingoes，my_dict有点linux的lingoes 感觉，简单实用（如果没用过，可以借鉴下lingoes的功能和UI）。

**Comment by yzcyayaya** [comment]
目前我使用的utools进行的翻译

**Comment by templklklk** [comment]
> 目前我使用的utools进行的翻译

我改用[crow-translate](https://github.com/crow-translate/crow-translate)了
