### ISSUE TITLE
是否考虑出一个源码运行教程？

### ISSUE THREAD

**Issue by infopensource** [xxNull-lsk/my_dict#4]
我想为arch构建一个版本，但是我本地运行不起来，希望能得到帮助

**Comment by xxNull-lsk** [comment]
已经提供源码运行和简单的arch系统的包。
不过，我对arch系统了解很少（几个小时前才刚刚按照教程第一次安装成功），所谓的包也仅仅是个tar。

**Comment by xxNull-lsk** [comment]
另外，arch系统中暂时还不支持ocr取词
