### ISSUE TITLE
能不能自动设置焦点在输入框中 ?

### ISSUE THREAD

**Issue by xhao79** [xxNull-lsk/my_dict#7]
使用快捷键呼出主界面后, 能不能设置输入焦点。比如,
如果是 "词典" 界面, 能不能将输入焦点设在 "搜索单词" 输入框中 ？ 
如果是 "翻译" 界面, 则自动设置 输入焦点 在 "粘贴"框 中?
这样可以直接输入要查询/翻译的内容, 而不需要使用鼠标手动设置输入焦点，再输入内容 ?

**Comment by xxNull-lsk** [comment]
最新版已经解决
